name: Pylint

# Ce que l'on spécifie dans le on, déclanche les actions que l'on définit dans jobs !
on: 
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]
    
# Ici, on définit les différentes actions que l'on veut produire si l'une des conditions définies dans le on est satisfaite.
jobs: 
  build:
    runs-on: ubuntu-latest # moteur de traitement
    steps:
    - uses: actions/checkout@v4 # veut dire qu'on fait un git clone de notre projet
    - name: Set up Python 3.11.14
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.14
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
